name: calendar
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  excellent_loading: ^1.0.6
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  pull_to_refresh: ^2.0.0
  permission_handler: ^11.4.0
  provider: ^6.1.2
  convert: ^3.1.2
  get_storage: ^2.1.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  otp_pin_field: ^1.4.0
  get: ^4.7.2
  jwt_decode: ^0.3.1
  syncfusion_flutter_charts: ^28.2.12
  fl_chart: ^0.70.2
  flutter_slidable: ^4.0.0
  awesome_dialog: ^3.2.1
  carousel_slider: ^5.0.0
  open_file: ^3.5.10
  jwt_decoder: ^2.0.1
  staggered_grid_view_flutter: ^0.0.4
  image_stack: ^2.1.1
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  file_picker: ^9.2.2
  animate_do: ^4.2.0
  dots_indicator: ^4.0.1
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.4
  flutter_device_type: ^0.4.0
  share_plus: ^10.1.4
  pdf: ^3.11.3
  screenshot: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  animated_bottom_navigation_bar: ^1.4.0
  flutter_tts: ^4.2.2
  just_audio: ^0.10.0
  flutter_audio_waveforms: ^1.2.1+8
  app_links: ^6.4.0
  flutter_secure_storage: ^9.2.4
  go_router: ^15.1.1
  flutter_dotenv: ^5.2.1
  percent_indicator: ^4.2.5
  another_flushbar: ^1.12.30
  internet_connection_checker: ^3.0.1
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_lints: ^5.0.0

  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logoios.jpg"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/logo/logoios.jpg"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/logo/posmobile1.png" 
    background_color: "#FFFFFF"  
    theme_color: "#FFFFFF"  
  windows:
    generate: true
    image_path: "assets/logo/posmobile1.png"  
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/logo/posmobile1.png" 

flutter:

  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
    - .env.staging
    - assets/logo/
    - assets/images/
    - assets/onboarding/

  fonts:
    - family: KantumruyPro
      fonts:
      - asset: assets/fonts/kantumruy-pro-khmer-400-normal.ttf
        weight: 400
      - asset: assets/fonts/kantumruy-pro-khmer-500-normal.ttf
        weight: 500
      - asset: assets/fonts/kantumruy-pro-khmer-600-normal.ttf
        weight: 600
      - asset: assets/fonts/kantumruy-pro-khmer-700-normal.ttf
        weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
    - family:  NewsIcon
      fonts:
        - asset: assets/fonts/NewsIcon.ttf
flutter_native_splash:
  color: "#002458" 
  image: assets/logo/posmobile1.png
  android: true
  ios: true
  fullscreen: true