name: calendar
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  excellent_loading: ^1.0.6
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  pull_to_refresh: ^2.0.0
  permission_handler: ^11.4.0
  provider: ^6.1.2
  convert: ^3.1.2
  get_storage: ^2.1.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  otp_pin_field: ^1.4.0
  get: ^4.7.2
  jwt_decode: ^0.3.1
  syncfusion_flutter_charts: ^28.2.12
  fl_chart: ^0.70.2
  flutter_slidable: ^4.0.0
  awesome_dialog: ^3.2.1
  carousel_slider: ^5.0.0
  open_file: ^3.5.10
  jwt_decoder: ^2.0.1
  staggered_grid_view_flutter: ^0.0.4
  image_stack: ^2.1.1
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  file_picker: ^9.2.2
  animate_do: ^4.2.0
  dots_indicator: ^4.0.1
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.3
  flutter_device_type: ^0.4.0
  share_plus: ^10.1.4
  pdf: ^3.11.3
  screenshot: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  animated_bottom_navigation_bar: ^1.4.0
  flutter_tts: ^4.2.2
  just_audio: ^0.10.0
  flutter_audio_waveforms: ^1.2.1+8
  app_links: ^6.4.0
  firebase_core: ^3.13.0
  firebase_dynamic_links: ^6.1.5
  flutter_secure_storage: ^9.2.4
  go_router: ^15.1.1
  flutter_dotenv: ^5.2.1
  percent_indicator: ^4.2.5
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/posmobile1.png"
  adaptive_icon_background: "#FFFFFF"  # Set a background color for adaptive icons
  adaptive_icon_foreground: "assets/logo/posmobile1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/posmobile1.png"  # Ensure this path is correct
    background_color: "#FFFFFF"  # Ensure this is the correct hex color code
    theme_color: "#FFFFFF"  # Ensure this is the correct hex color code
  windows:
    generate: true
    image_path: "assets/logo/posmobile1.png"  # Ensure this path is correct
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/posmobile1.png"  # Ensure this path is correct

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod
    - .env.staging
    - assets/logo/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: KantumruyPro
      fonts:
      - asset: assets/fonts/kantumruy-pro-khmer-400-normal.ttf
        weight: 400
      - asset: assets/fonts/kantumruy-pro-khmer-500-normal.ttf
        weight: 500
      - asset: assets/fonts/kantumruy-pro-khmer-600-normal.ttf
        weight: 600
      - asset: assets/fonts/kantumruy-pro-khmer-700-normal.ttf
        weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
    - family:  NewsIcon
      fonts:
        - asset: assets/fonts/NewsIcon.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
